---
title: "MilestoneExploratoryDataAnalysis"
author: "Mathew Bramson"
date: "December 27, 2015"
output: html_document
---

# Executive Summary

This report contains exploratory data analysis and initial findings from a dataset of US Tweets, Blogs, and News. The source data consists of various corpora scraped from publicly available sources.

The original datasets as well as documentation can be found at http://www.corpora.heliohost.org/

# Data Preparation

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE)
```

```{r load_packages, message=FALSE}
library(quanteda)
library(RColorBrewer)
```

## Building Corpora

```{r load_corpora, message=FALSE}
tweet.con <- file("en_US.twitter.txt")
tweet.corpus <- corpus(readLines(tweet.con))
close(tweet.con)

blog.con <- file("en_US.blogs.txt")
blog.corpus <- corpus(readLines(blog.con))
close(blog.con)

news.con <- file("en_US.news.txt", open="rb")
news.corpus <- corpus(readLines(news.con, encoding="UTF-8"))
close(news.con)
```

# Exploratory Data Analysis

```{r tweet_dfm}
tweet.dfm <- dfm(tweet.corpus, ignoredFeatures = stopwords("english"))
plot(tweet.dfm, max.words=30, colors = brewer.pal(6, "Dark2"), scale=c(4, .5))
```

```{r blog_dfm}
blog.dfm <- dfm(blog.corpus, ignoredFeatures = stopwords("english"))
plot(blog.dfm, max.words=30, colors = brewer.pal(6, "Dark2"), scale=c(4, .5))
```

```{r news_dfm}
news.dfm <- dfm(news.corpus, ignoredFeatures = stopwords("english"))
plot(news.dfm, max.words=30, colors = brewer.pal(6, "Dark2"), scale=c(4, .5))
```